DROP DATABASE IF EXISTS im;
CREATE DATABASE im DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT SELECT, INSERT, UPDATE, DELETE ON im.* TO 'hhou1'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS t_user (
    f_id INT(40) NOT NULL AUTO_INCREMENT COMMENT '用户的唯一id号',
    f_name VARCHAR(20) NOT NULL COMMENT '用户昵称，不可为空',
    f_pass VARCHAR(20) NOT NULL COMMENT '用户的密码，加密后的',
    f_desc VARCHAR(20) NOT NULL COMMENT '用户简介，一句话介绍，可以用作此用户的座右铭',
    f_updatetime TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', 
    PRIMARY KEY (f_id),
    KEY(f_id, f_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

